apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: michael.kemna@gmail.com
    http01: {}
    privateKeySecretRef:
      key: ""
      name: letsencrypt-prod
server: https://acme-v02.api.letsencrypt.org/directory
